FROM node:18

WORKDIR /app

# Install dependencies first
COPY package*.json ./
RUN npm install

# Copy rest (in dev, we’ll override this with a volume mount anyway)
COPY . .

EXPOSE 4200

CMD ["npm", "run", "start:devcontainer"]
